
[build]

  publish = "dist"
  command = "npm install && npm run build"
  base = "app" # Aunque ya lo tienes en la UI, no está de más ser explícito
 
[redirects]
  from = "/*"
  to = "/index.html"
  status = 200
